services:
  mssql:
    container_name: mssql
    build:
      context: ./mssql
      dockerfile: Dockerfile
    expose:
      - 1433
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      MSSQL_NEO4J_SETUP_READER_USERNAME: ${MSSQL_NEO4J_SETUP_READER_USERNAME}
      MSSQL_NEO4J_SETUP_READER_PASSWORD: ${MSSQL_NEO4J_SETUP_READER_PASSWORD}
      MSSQL_DBGATE_READER_USERNAME: ${MSSQL_DBGATE_READER_USERNAME}
      MSSQL_DBGATE_READER_PASSWORD: ${MSSQL_DBGATE_READER_PASSWORD}
      ACCEPT_EULA: Y
      MSSQL_PID: Developer
    volumes:
      - mssql_data:/var/opt/mssql
    entrypoint: ./entrypoint.sh
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools18/bin/sqlcmd", "-U", "sa", "-P", "${MSSQL_SA_PASSWORD}", "-S", "localhost", "-C", "-i", "/usr/config/check_setup.sql", "-v", "MSSQL_DBGATE_READER_USERNAME=${MSSQL_DBGATE_READER_USERNAME}", "-b" ]
      start_period: 120s

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    expose:
      - 11434
    environment:
      OLLAMA_NO_CLOUD: 1
      OLLAMA_FLASH_ATTENTION: 1
      OLLAMA_KV_CACHE_TYPE: q4_0
    volumes:
      - ollama_data:/root/.ollama
    restart: on-failure:3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    healthcheck:
      test: [ "CMD", "ollama", "list" ]
      start_period: 120s

  ollama_setup:
    container_name: ollama_setup
    image: ollama/ollama:latest
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      OLLAMA_HOST: "http://ollama:11434"
      MODELS: ${OLLAMA_LLM},${OLLAMA_EMBEDDING},${OLLAMA_THINK}
    volumes:
      - ./ollama_setup/setup_models.sh:/setup_models.sh
    entrypoint:
      - /bin/bash
      - /setup_models.sh
    restart: "no"

  neo4j:
    container_name: neo4j
    image: neo4j:latest
    expose:
      - 7687
    ports:
      - "127.0.0.1:${NEO4J_HTTP_PORT}:7474"
      - "127.0.0.1:${NEO4J_BOLT_PORT}:7687"
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME}/${NEO4J_PASSWORD}
    volumes:
      - neo4j_logs:/logs
      - neo4j_conf:/conf
      - neo4j_data:/data
      - neo4j_plugins:/plugins
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "neo4j", "status" ]
      start_period: 120s

  neo4j_setup:
    container_name: neo4j_setup
    build:
      context: ./neo4j_setup
      dockerfile: Dockerfile
    depends_on:
      mssql:
        condition: service_healthy
      neo4j:
        condition: service_healthy
      ollama:
        condition: service_healthy
      ollama_setup:
        condition: service_completed_successfully
    environment:
      UV_NO_DEV: 1
      PYTHONDONTWRITEBYTECODE: 1
      UV_PROJECT_ENVIRONMENT: /opt/venv
      MSSQL_NEO4J_SETUP_READER_USERNAME: ${MSSQL_NEO4J_SETUP_READER_USERNAME}
      MSSQL_NEO4J_SETUP_READER_PASSWORD: ${MSSQL_NEO4J_SETUP_READER_PASSWORD}
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      OLLAMA_LLM: ${OLLAMA_LLM}
      OLLAMA_EMBEDDING: ${OLLAMA_EMBEDDING}
    volumes:
      - ./neo4j_setup:/usr/src/app
    entrypoint:
      - uv
      - run
      - -m
      - main
    restart: "no"

  dbgate:
    container_name: dbgate
    build:
      context: ./dbgate
      dockerfile: Dockerfile
    depends_on:
      mssql:
        condition: service_healthy
    ports:
      - "127.0.0.1:${DBGATE_PORT}:3000"
    environment:
      CONNECTIONS: con1
      LABEL_con1: mssql
      ENGINE_con1: mssql@dbgate-plugin-mssql
      SERVER_con1: mssql
      PORT_con1: 1433
      USER_con1: ${MSSQL_DBGATE_READER_USERNAME}
      PASSWORD_con1: ${MSSQL_DBGATE_READER_PASSWORD}
    volumes:
      - dbgate_data:/root/.dbgate
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:3000/health" ]
      start_period: 120s

  streamlit:
    container_name: streamlit
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    depends_on:
      ollama:
        condition: service_healthy
      ollama_setup:
        condition: service_completed_successfully
      neo4j:
        condition: service_healthy
      neo4j_setup:
        condition: service_completed_successfully
      mssql:
        condition: service_healthy
    ports:
      - "127.0.0.1:${STREAMLIT_PORT}:8501"
    environment:
      UV_NO_DEV: 1
      PYTHONDONTWRITEBYTECODE: 1
      UV_PROJECT_ENVIRONMENT: /opt/venv
    volumes:
      - ./streamlit_app:/usr/src/app
    entrypoint:
      - uv
      - run
      - -m
      - streamlit
      - run
      - ./main.py
    restart: on-failure:3
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8501/" ]
      start_period: 120s

volumes:
  mssql_data:
  ollama_data:
  dbgate_data:
  neo4j_logs:
  neo4j_conf:
  neo4j_data:
  neo4j_plugins:
