services:
  mssql:
    container_name: mssql
    build:
      context: ./mssql
      dockerfile: Dockerfile
    expose:
      - 1433
    env_file: ./mssql/.env
    environment:
      MSSQL_DBGATE_READER_USERNAME: ${MSSQL_DBGATE_READER_USERNAME}
      MSSQL_DBGATE_READER_PASSWORD: ${MSSQL_DBGATE_READER_PASSWORD}
      MSSQL_CONTEXT_RETRIEVER_READER_USERNAME: ${MSSQL_CONTEXT_RETRIEVER_READER_USERNAME}
      MSSQL_CONTEXT_RETRIEVER_READER_PASSWORD: ${MSSQL_CONTEXT_RETRIEVER_READER_PASSWORD}
    volumes:
      - mssql-data:/var/opt/mssql
    entrypoint: ./entrypoint.sh
    restart: on-failure:3

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    expose:
      - 11434
    env_file: ./ollama/.env
    volumes:
      - ollama-data:/root/.ollama
      - ./ollama/entrypoint.sh:/entrypoint.sh
    entrypoint: /entrypoint.sh
    restart: on-failure:3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

  context_retriever:
    container_name: context_retriever
    build:
      context: ./context-retriever
      dockerfile: Dockerfile
    depends_on:
      - mssql
    expose:
      - 8000
    env_file: ./context-retriever/.env
    environment:
      MSSQL_PORT: 1433
      MSSQL_CONTEXT_RETRIEVER_READER_USERNAME: ${MSSQL_CONTEXT_RETRIEVER_READER_USERNAME}
      MSSQL_CONTEXT_RETRIEVER_READER_PASSWORD: ${MSSQL_CONTEXT_RETRIEVER_READER_PASSWORD}
    volumes:
      - ./context-retriever:/usr/src/app
    entrypoint:
      - uv
      - run
      - -m
      - fastapi
      - run
    restart: on-failure:3

  dbgate:
    container_name: dbgate
    image: dbgate/dbgate:latest
    depends_on:
      - mssql
    ports:
      - "127.0.0.1:${DBGATE_PORT}:3000"
    env_file: ./dbgate/.env
    environment:
      USER_con1: ${MSSQL_DBGATE_READER_USERNAME}
      PASSWORD_con1: ${MSSQL_DBGATE_READER_PASSWORD}
      PORT_con1: 1433
    volumes:
      - dbgate-data:/root/.dbgate
    restart: on-failure:3

volumes:
  mssql-data:
  ollama-data:
  dbgate-data:
