#!/bin/bash

DBSTATUS=1
ERRCODE=1
until [[ "$DBSTATUS" -eq 0 && "$ERRCODE" -eq 0 ]]; do
    sleep 1
    DBSTATUS=$(sqlcmd -U sa -P "$MSSQL_SA_PASSWORD" -S localhost -C -t 1 -h -1 -Q "SET NOCOUNT ON; Select SUM(state) from sys.databases")
    ERRCODE=$?
    if [[ -z "$DBSTATUS" ]]; then
        DBSTATUS=1
    fi
done

sqlcmd -U sa -P "$MSSQL_SA_PASSWORD" -S localhost -C -d master -i /usr/config/setup.sql -v MSSQL_DBGATE_READER_USERNAME="$MSSQL_DBGATE_READER_USERNAME" MSSQL_DBGATE_READER_PASSWORD="$MSSQL_DBGATE_READER_PASSWORD" MSSQL_CONTEXT_RETRIEVER_READER_USERNAME="$MSSQL_CONTEXT_RETRIEVER_READER_USERNAME" MSSQL_CONTEXT_RETRIEVER_READER_PASSWORD="$MSSQL_CONTEXT_RETRIEVER_READER_PASSWORD"