[project]
name = "context-retriever"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.141.1",
    "mssql-python>=1.13.0",
    "toon-format",
]

[tool.uv.sources]
toon-format = { git = "https://github.com/toon-format/toon-python.git" }

[tool.fastapi]
entrypoint = "main:app"